-- ============================================================
--  Voin 초기 스키마 (V1)
--  현재 JPA 엔티티 기준으로 Hibernate 가 생성한 PostgreSQL DDL 을 정본으로 사용.
--  prod 프로필은 ddl-auto: validate 이므로 이 스키마가 엔티티와 정확히 일치해야 함.
--  엔티티 변경 시에는 이 파일을 수정하지 말고 V2__*.sql 등 새 마이그레이션을 추가할 것.
-- ============================================================

create table coins (
    id bigint generated by default as identity,
    name varchar(50) not null unique,
    description varchar(500),
    color varchar(7),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table members (
    id uuid not null,
    kakao_id varchar(50) not null unique,
    nickname varchar(10) not null,
    profile_image varchar(500),
    friend_code varchar(5) not null unique,
    is_active boolean not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table keywords (
    id bigint generated by default as identity,
    coin_id bigint not null,
    name varchar(30) not null,
    description varchar(300),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table stories (
    id bigint generated by default as identity,
    member_id uuid not null,
    title varchar(255) not null,
    content varchar(5000) not null,
    story_type varchar(30) not null check (story_type in ('DAILY_DIARY','EXPERIENCE_REFLECTION')),
    situation_context varchar(100),
    answer1 varchar(2000),
    answer2 varchar(2000),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table cards (
    id bigint generated by default as identity,
    creator_id uuid not null,
    owner_id uuid not null,
    target_member_id uuid not null,
    story_id bigint not null,
    keyword_id bigint not null unique,
    content varchar(1000),
    is_public boolean not null,
    is_gift boolean not null,
    situation_context varchar(100),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table member_coins (
    id bigint generated by default as identity,
    member_id uuid not null,
    coin_id bigint not null,
    count integer not null check (count>=0),
    first_obtained_at timestamp(6) not null,
    last_obtained_at timestamp(6) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint idx_member_coin_unique unique (member_id, coin_id)
);

create table friends (
    id bigint generated by default as identity,
    from_member_id uuid,
    to_member_id uuid,
    status varchar(255) not null check (status in ('PENDING','ACCEPTED','REJECTED')),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

-- 인덱스
create index idx_coin_name on coins (name);

create index idx_member_kakao_id on members (kakao_id);
create index idx_member_friend_code on members (friend_code);

create index idx_keyword_coin_id on keywords (coin_id);
create index idx_keyword_name on keywords (name);
create index idx_keyword_coin_name on keywords (coin_id, name);

create index idx_story_member_id on stories (member_id);
create index idx_story_type on stories (story_type);
create index idx_story_created_at on stories (created_at);

create index idx_card_creator_id on cards (creator_id);
create index idx_card_owner_id on cards (owner_id);
create index idx_card_target_member_id on cards (target_member_id);
create index idx_card_story_id on cards (story_id);
create index idx_card_keyword_id on cards (keyword_id);
create index idx_card_public on cards (is_public);

create index idx_member_coin_member_id on member_coins (member_id);
create index idx_member_coin_coin_id on member_coins (coin_id);

-- 외래키
alter table if exists keywords
    add constraint fk_keyword_coin foreign key (coin_id) references coins;

alter table if exists cards
    add constraint fk_card_creator foreign key (creator_id) references members;
alter table if exists cards
    add constraint fk_card_owner foreign key (owner_id) references members;
alter table if exists cards
    add constraint fk_card_target_member foreign key (target_member_id) references members;
alter table if exists cards
    add constraint fk_card_story foreign key (story_id) references stories;
alter table if exists cards
    add constraint fk_card_keyword foreign key (keyword_id) references keywords;

alter table if exists friends
    add constraint fk_friend_from_member foreign key (from_member_id) references members;
alter table if exists friends
    add constraint fk_friend_to_member foreign key (to_member_id) references members;
