-- 카드 좋아요 (회원-카드 1회, 유니크)
create table card_likes (
    id bigint generated by default as identity,
    member_id uuid not null,
    card_id bigint not null,
    created_at timestamp(6) not null,
    primary key (id),
    constraint uk_card_like unique (member_id, card_id)
);

create index idx_card_like_card_id on card_likes (card_id);
