-- 사용자 알림
create table notifications (
    id bigint generated by default as identity,
    recipient_id uuid not null,
    type varchar(30) not null,
    message varchar(255) not null,
    link_type varchar(20),
    link_id bigint,
    is_read boolean not null default false,
    created_at timestamp(6) not null,
    primary key (id)
);

create index idx_notification_recipient on notifications (recipient_id);
